package com.samsung.android.otpforwarder.core.model

import kotlinx.datetime.Instant

/**
 * Represents a single incoming SMS message as received from the Android
 * telephony layer. This is a pure data model — no Android framework types.
 *
 * @param id             Stable identifier generated by the parser (millis-based UUID fallback).
 * @param sender         The originating address (phone number or alphanumeric sender ID).
 * @param body           Full message body as a single concatenated string (multi-part PDUs merged).
 * @param receivedAt     Timestamp from the PDU header (or system clock when unavailable).
 * @param subscriptionId SIM slot subscription ID; -1 when the device is single-SIM or unknown.
 */
data class SmsMessage(
    val id: String,
    val sender: String,
    val body: String,
    val receivedAt: Instant,
    val subscriptionId: Int = -1,
)
